### ISSUE TITLE
Segfault when `Promise::result` is called

### ISSUE THREAD

**Issue by Arshia001** [Redfire75369/spiderfire#38]
I know this is a known issue:

```rust
	/// Returns the result of the [Promise].
	///
	/// ### Note
	/// Currently leads to a sefault.
	pub fn result<'cx>(&self, cx: &'cx Context) -> Value<'cx> {
		let mut value = Value::undefined(cx);
		unsafe { JS_GetPromiseResult(self.handle().into(), value.handle_mut().into()) }
		value
	}
```

However, I'm wondering why this happens and what has to happen to fix it? Our usecase depends heavily on promises and we've been running into the segfault.

Here's a stack trace just in case it proves useful:

```
thread '<unnamed>' panicked at /Users/arshia/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5caf17f/mozjs-sys/src/jsimpls.rs:420:9:
assertion failed: *self.stack == self as *mut _ as usize as _
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
   3: mozjs_sys::jsimpls::<impl mozjs_sys::jsgc::Rooted<T>>::remove_from_root_stack
             at /Users/arshia/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5caf17f/mozjs-sys/src/jsimpls.rs:420:9
   4: <ion::context::Context as core::ops::drop::Drop>::drop
             at /Users/arshia/repos/wasmer/spiderfire/ion/src/context.rs:222:3
   5: core::ptr::drop_in_place<ion::context::Context>
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
   6: wasmer_winter::ion_runner::performance::test_futures::wrapper::inner::{{closure}}
             at ./src/ion_runner/performance.rs:34:5
   7: runtime::promise::future_to_promise::{{closure}}
             at /Users/arshia/repos/wasmer/spiderfire/runtime/src/promise.rs:27:69
   8: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/core.rs:184:17
   9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/loom/std/unsafe_cell.rs:14:9
  10: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/core.rs:174:13
  11: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/harness.rs:480:19
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  13: std::panicking::try::do_call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  14: ___rust_try
  15: std::panicking::try
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  16: std::panic::catch_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  17: tokio::runtime::task::harness::poll_future
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/harness.rs:468:18
  18: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/harness.rs:104:27
  19: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/harness.rs:57:15
  20: tokio::runtime::task::raw::poll
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/raw.rs:194:5
  21: tokio::runtime::task::raw::RawTask::poll
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/raw.rs:134:18
  22: tokio::runtime::task::LocalNotified<S>::run
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/task/mod.rs:385:9
  23: tokio::task::local::LocalSet::tick::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:578:54
  24: tokio::coop::with_budget::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:102:9
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  26: std::thread::local::LocalKey<T>::with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  27: tokio::coop::with_budget
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:95:5
  28: tokio::coop::budget
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:72:5
  29: tokio::task::local::LocalSet::tick
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:578:31
  30: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:814:16
  31: tokio::task::local::LocalSet::with::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:633:13
  32: std::thread::local::LocalKey<T>::try_with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  33: std::thread::local::LocalKey<T>::with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  34: tokio::task::local::LocalSet::with
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:616:9
  35: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:800:9
  36: tokio::task::local::LocalSet::run_until::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/task/local.rs:536:19
  37: wasmer_winter::ion_runner::IonRunner::spawn_thread::{{closure}}::{{closure}}
             at ./src/ion_runner/mod.rs:343:73
  38: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  39: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:543:48
  40: tokio::coop::with_budget::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:102:9
  41: std::thread::local::LocalKey<T>::try_with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  42: std::thread::local::LocalKey<T>::with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  43: tokio::coop::with_budget
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:95:5
  44: tokio::coop::budget
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/coop.rs:72:5
  45: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:543:25
  46: tokio::runtime::basic_scheduler::Context::enter
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:367:19
  47: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:542:36
  48: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:613:57
  49: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/macros/scoped_tls.rs:61:9
  50: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:613:27
  51: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:533:19
  52: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/basic_scheduler.rs:179:24
  53: tokio::runtime::Runtime::block_on
             at /Users/arshia/.cargo/git/checkouts/tokio-2eb71367495b4da5/2be2588/tokio/src/runtime/mod.rs:486:46
  54: wasmer_winter::ion_runner::IonRunner::spawn_thread::{{closure}}
             at ./src/ion_runner/mod.rs:337:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

and here's the code in `test_futures`:

```rs
#[js_fn]
fn test_futures<'cx>(cx: &'cx Context, promise: ion::Promise) -> Option<ion::Promise<'cx>> {
    let cx2 = unsafe { Context::new_unchecked(cx.as_ptr()) };
    let p = cx2
        .root_persistent_object(promise.get())
        .handle()
        .into_handle();

    future_to_promise::<_, _, ion::Exception>(cx, async move {
        let promise = unsafe { ion::Promise::from_unchecked(Local::from_raw_handle(p)) };

        println!("Waiting for promise");

        let v = promise.to_future::<String>(&cx2, false, ()).await?;

        println!("The wait is over, result: {v}");

        cx2.unroot_persistent_object(promise.get());

        Ok(v)
    })
}
```

where `Promise::to_future` is something I'm currently working on.

**Comment by Redfire75369** [comment]
Last I checked, I fixed the segfault on `Promise::result` already, and it should have only happened on Windows (ABI issues).
Could I see the contents of however `Promise::to_future` is implemented?

**Comment by Redfire75369** [comment]
I think I've found it. This isn't really documented anywhere since I was looking to change it eventually, but `Local::Rooted` cannot be stored on the heap. It relies on LIFO destruction, either through `mozjs::rooted!` or `Context::root_*`, because GC tracing relies on a linked list.

**Comment by Arshia001** [comment]
I see. Let me see if that fixes it.

**Comment by Redfire75369** [comment]
Both of these implicitly use `Context::root_*` implicitly instead of `Context::root_persistent_object`
```rs
					let f = Function::from_closure_once(
						self.cx,
						"__promise_waker",
						Box::new(move |args: &mut crate::Arguments<'_>| {
							waker.wake();
							Ok(Value::undefined(args.cx()))
						}),
						0,
						PropertyFlags::empty(),
					);
					let f2 = Function::from_object(self.cx, &f.to_object(self.cx).into_local()).unwrap();
```
What you'd need to do is convert the function to an object, root it persistently and then back into a function (functions are objects in trenchcoats, so that should work).

**Comment by Redfire75369** [comment]
Could you perhaps try having this in the test code (`future_to_promise` body) instead?
```rs
        let v = promise.to_future::<String>(&cx2, false, ()).await;

        println!("The wait is over, result");

        cx2.unroot_persistent_object(promise.get());

        v
```

**Comment by Arshia001** [comment]
I tried persistently rooting the function, still no luck:

```rust
			PromiseState::Pending => {
				if let None = self.reaction_func {
					let waker = cx.waker().clone();

					let f = Function::from_closure_once(
						self.cx,
						"__promise_waker",
						Box::new(move |args: &mut crate::Arguments<'_>| {
							waker.wake();
							Ok(Value::undefined(args.cx()))
						}),
						0,
						PropertyFlags::empty(),
					);

					let f = self.cx.root_persistent_object((*f.to_object(self.cx)).get());

					// A promise only resolves or fails once, so we can reuse the same ClosureOnce
					unsafe { AddPromiseReactions(self.cx.as_ptr(), promise.handle().into(), f.handle().into(), f.handle().into()) };
					self.get_mut().reaction_func = Some(f.get());
				}

				std::task::Poll::Pending
			}
```

**Comment by Arshia001** [comment]
That'd be cool to have.

I'm gonna keep messing with the code to see what's breaking it. Do you have any recommendations on how one might go about investigating this kind of issue other than staring at code? 😄

**Comment by Redfire75369** [comment]
I've been messing around a bit. The only issue seems to be
```rs
		let promise = unsafe { Promise::from_unchecked(self.cx.root_object(self.promise)) };
```

**Comment by Redfire75369** [comment]
Ok I've figured it out. The issue is actually the `Value::undefined` in `Promise::result`. The issue is that rooting values also happens in the event loop as well, on completion of promises, so the `stackRoots` are modified and some of the invariants of `Rooted` are broken.
I don't really have a fix to this though, other than the aforementioned new rooting strategy.

**Comment by Redfire75369** [comment]
On the other hand, do note that `ion::future;:Promise` exists, which should work for your usecase.

**Comment by Arshia001** [comment]
Oh. That's good to know.

Thanks for looking into this, I really appreciate the help!

**Comment by Arshia001** [comment]
Fun fact: I switched to `ion::future::PromiseFuture` and the code is still failing with the same error:

```rust
    future_to_promise::<_, _, ion::Exception>(cx, async move {
        let promise = unsafe { ion::Promise::from_unchecked(Local::from_raw_handle(p)) };

        println!("Waiting for promise");

        let v = PromiseFuture::new(&cx2, &promise).await.unwrap();
        let v = String::from_value(&cx2, &cx2.root_value(v).into(), true, ()).unwrap();

        println!("The wait is over, result: {v}");

        cx2.unroot_persistent_object(promise.get());

        Ok(v)
    })
```

**Comment by Redfire75369** [comment]
Yeah, I figured, almost certainly the same issue as before.

**Comment by Arshia001** [comment]
@Redfire75369 I've narrowed it down to rooting an object (and only an object) *before* awaiting a future. This is the current code that's failing:

```rust
        let resolved = Object::null(&cx2); // This causes the segfault
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
        Ok(mozjs::jsval::NullValue())
```

The same thing doesn't happen if I use persistent rooting. So, I guess I can use only persistent rooting (including in `Promise::add_reactions`) as a temporary work-around.

**Comment by Arshia001** [comment]
The error only happens in the presence of a `setTimeout` call I'm using in my script. If I comment that out, it seems like everything works correctly (am still investigating though).

**Comment by Arshia001** [comment]
I believe the main issue is that we're using rooted values at all in futures. Futures' locals live on the heap, and rooted values are supposed to only ever be placed on the stack.

I wonder if it's possible to automatically root stuff to the heap within the context of a future? It's certainly possible to detect when code is being executed from within a future (using e.g. a thread local), but I wonder if we can make the context support heap rooting.

We could also pass a separate kind of context (say, a `FutureContext`) into futures spawned with `future_to_promise`, but that would require a *lot* of work, since all the code that works with contexts, which is pretty much all the code in Spiderfire, must now be made aware of the new type (maybe through a trait?)

**Comment by Redfire75369** [comment]
That's not quite the issue, it's an interaction between the event loop and whatever code is running in the future.

There are two instances of `Context`, which each hold their rooted values separately, and hence drop them separately. When dropped, the Context unroots *all* it's values, which may not match up with the LIFO ordering overall of its values and the other instance's values.

**Comment by Redfire75369** [comment]
It goes something like this


Let say there are two Context instances: A (main/event loop) and B (future)

1. A roots a value #0
2. B roots a value #1
3. A roots a value #2
4. B is dropped, unrooting the value
- Trips the `*self.stack == self` assertion, which checks if the rooted value is at the top of "stack".
- Value #2 must be dropped first then Value #1, then Value #0

As ion's rooting is currently architected, that's impossible to enforce.

**Comment by Arshia001** [comment]
Yes, I understand the issue. I'm under the impression that stack rooting was designed that way precisely because values on the stack are created and dropped in LIFO order. When you put something on the heap (such as a future) it can easily break that invariant since it's now being dropped (or, in C++ terms, its destructor called) at whatever point the code wants it to. I'll try the heap thing and see how it goes.

**Comment by Redfire75369** [comment]
It's not inherently an issue with the heap, it's moreso with how futures work, and that they can run concurrently with the main event loop.

I'm working on the new heap-based approach but that'll take a while, there's a lot of tiny and non-obvious issues that need to be worked around.

**Comment by Arshia001** [comment]
So, the heap thing didn't exactly work out as I intended, but I have found a solution to make everything work:

```rust
        let v = PromiseFuture::new(&cx2, &promise);
        let cx3 = unsafe { Context::new_unchecked(cx2.as_ptr()) };
        drop(cx2);
        v.await.unwrap();
        let v = promise.result(&cx3);
```

basically, all the rooted values are kept around unnecessarily across the await point because the Spiderfire context holds on to all of them and only drops everything right at the end of its own lifetime; so creating a new, empty `cx3` for use after the await point means we correctly unroot everything before awaiting and there will be no more errors.

Here's the question: why doesn't Spiderfire do the same thing as mozjs's own `RootedGuard`? Why not unroot values when the corresponding `Local` is dropped? I assume there's a good reason the context is designed the way it is.

**Comment by Arshia001** [comment]
> It's not inherently an issue with the heap, it's moreso with how futures work, and that they can run concurrently with the main event loop.

Concurrently, yes, but not in parallel. If we don't hold rooted values across await points, nothing can go wrong.

> I'm working on the new heap-based approach but that'll take a while, there's a lot of tiny and non-obvious issues that need to be worked around.

I tried going down this specific rabbit hole today. It's not easy to make everything automagically work out whether we're awaiting or not (at least without considerable changes to everything). I think the programmer always has to be aware of await points. We just need to provide the right tools:

* don't keep values rooted unnecessarily
* provide some sort of wrapper over `Heap<T>` that's easier to use, may be with `handle(&self, cx)` and `handle_mut(&self, cx)` convenience methods.

**Comment by Redfire75369** [comment]
`Local` doesn't automatically unroot on drop so that they can be properly returned without breaking LIFO ordering. That was done for ease of use since outparams (MutableHandle) aren't as common a pattern in rust and don't map well to traits for example.

**Comment by Arshia001** [comment]
That makes sense.

I'm thinking about making `future_to_promise` unsafe with a warning that mentions this issue. Also, as a convenience, `PromiseFuture` should take the context by value, drop it and return a new one after the promise completes.

There's nothing we can do that guarantees correctness for native futures (that I can think of), people just have to be extra careful with keeping contexts alive. One thing we can to help people along is a `Context::await_native_future` mathod that does the dropping and recreating automatically.

I also want to create the `ion::Heap` type I mentioned above to help with keeping values alive across await points (and maybe as part of structs).

**Comment by Arshia001** [comment]
FYI, I remembered where I'd seen the error before: when running multiple requests all at once. WinterJS may run multiple requests at once on the same thread and JS context, which caused interleaving of the promises.

**Comment by Redfire75369** [comment]
Here was my approach (not complete yet): [rewrite/root-heap](https://github.com/Redfire75369/spiderfire/tree/rewrite/root-heap)
Essentially, there's `Root<Box<Heap<*mut JSObject>>>` replaces `Local<'_, *mut JSObject>`. There's two main differences:
1. `Local::handle_mut` has no replacement (Use `rooted!`)
2. `Local::from_{,raw}_handle_{,mut}` and co. have no replacement. You must root before using the APIs.

**Comment by Arshia001** [comment]
So, does *everything* live on the heap if that's merged in? I wonder what the performance implications would be.

**Comment by Redfire75369** [comment]
Technically everything was already living on the heap. The performance impacts in terms of the tracing shouldn't be that bad. The main performance issue might be with dynamic dispatch.

**Comment by Arshia001** [comment]
I wonder if it's worth it, creating additional runtime overhead to have uniform support for futures. I can do some profiling once the code is ready.

**Comment by Arshia001** [comment]
OK, the results are in. This is from "vanilla" WinterJS, running against our forked version of Spiderfire:

```
wrk -t12 -c400 -d10s http://127.0.0.1:8080
Running 10s test @ http://127.0.0.1:8080
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.53ms   23.33ms 243.54ms   87.35%
    Req/Sec     9.09k     1.96k   15.35k    76.17%
  1086628 requests in 10.02s, 124.35MB read
  Socket errors: connect 0, read 421, write 9, timeout 0
Requests/sec: 108417.06
Transfer/sec:     12.41MB
```

this is from WinterJS running against the original Spiderfire master (I had to cut some functionality out, but nothing that would impact the test in a meaningful way. If anything, it should be ever so slightly faster now):

```
wrk -t12 -c400 -d10s http://127.0.0.1:8080
Running 10s test @ http://127.0.0.1:8080
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.55ms   18.86ms 148.91ms   87.00%
    Req/Sec     9.18k     1.58k   26.97k    77.72%
  1099181 requests in 10.10s, 83.86MB read
  Socket errors: connect 0, read 357, write 0, timeout 0
Requests/sec: 108786.93
Transfer/sec:      8.30MB
```

and this is from WinterJS running against the root-heap branch:

```
wrk -t12 -c400 -d10s http://127.0.0.1:8080
Running 10s test @ http://127.0.0.1:8080
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.48ms   18.09ms 168.10ms   87.72%
    Req/Sec     8.60k     2.02k   17.41k    76.51%
  1007125 requests in 10.03s, 76.84MB read
  Socket errors: connect 0, read 312, write 0, timeout 0
Requests/sec: 100387.62
Transfer/sec:      7.66MB
```

As you can see, the R/S number is now around 7.5% lower. Also, we're missing `<thing>.handle_mut()`, so it's not immediately clear how one should use native APIs that have no wrapper.

All in all, my 2 cents is that we should probably stick to the way the code was meant to be used by the people who wrote it in the first place, which is stack rooting and going to the heap only when necessary. But that's just my opinion.
