### ISSUE TITLE
Panic when printing a prototype

### ISSUE THREAD

**Issue by Arshia001** [Redfire75369/spiderfire#43]
From the latest commit on master:

```
> new File(['a'], 'b').__proto__
{
thread 'main' panicked at /Users/arshia/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/0a2efb9/mozjs-sys/src/jsval.rs:503:9:
assertion failed: self.is_double()
  "name": undefined,
thread 'main' panicked at /Users/arshia/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/0a2efb9/mozjs-sys/src/jsval.rs:503:9:
assertion failed: self.is_double()
  "lastModified": undefined,
}
```

It looks like the pretty-printing code tries to access the properties of the prototype object like a normal constructed object, which causes a panic.

**Comment by Redfire75369** [comment]
This should be fixed as of the latest commit, although it does also lead to a small problem with the instances themselves.
```js
> Blob.prototype
{
  "type": [Getter],
  "size": [Getter],
  "slice": function slice() {
      [native code]
  },
  "text": function text() {
      [native code]
  },
  "arrayBuffer": function arrayBuffer() {
      [native code]
  },
}
new URL("https://www.example.com")
URL {
  "protocol": [Getter/Setter],
  "port": [Getter/Setter],
  "href": [Getter/Setter],
  "origin": [Getter],
  "pathname": [Getter/Setter],
  "username": [Getter/Setter],
  "password": [Getter/Setter],
  "search": [Getter/Setter],
  "host": [Getter/Setter],
  "hostname": [Getter/Setter],
  "hash": [Getter/Setter],
  "searchParams": [Getter],
  "format": function format() {
      [native code]
  },
  "toString": function toString() {
      [native code]
  },
  "toJSON": function toJSON() {
      [native code]
  },
}
```
